### ISSUE TITLE
About modal (https://github.com/dcgtc/dgrants/blob/richard-ui3/app/src/components/About.vue)

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#122]
Dependent on #116

**Comment by carletex** [comment]
Hey @apbendi 

Richard is getting the contributor list from the public GitHub API (rate limit = 60 request/hour per IP). Do we want to make the list dynamic, should we hard-code it or maybe something in between (like fetching the list at build time and store it on a json file)? 

Also:
- Where do we get the build version?
- Link for Donate button?

Those are still **ToDo** on Richard's code.

I'm asking because I'm not sure if we wan't to do incremental PRs on these things, or we want a *final* version with everything working before merging to *main*.

P.S: Seems that the dependency #116 (PR #131) will be merged soon :)

![image](https://user-images.githubusercontent.com/2486142/130462421-677f2c18-048d-4b80-ad23-70f23290fb60.png)

**Comment by mds1** [comment]
Another idea that might be worth looking into: the ethereum.org repo has a bot that automatically opens a PR to add a new contributor whenever requested. For example, [this](https://github.com/ethereum/ethereum-org-website/pull/3598) was my first PR to that repo, and you can see the `@allcontributors` bot automatically opened a PR when it was prompted to by one of the repo maintainers. Looks like this is the bot: https://allcontributors.org/
