### ISSUE TITLE
Grant Round Manager Spec

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#40]
- [x] Rename the `GrantRoundFactory` to `GrantRoundManager`
- [x] Add an immutable variable `donationToken` to the Manager contract that is defined at deployment
- [x] Remove `_donationToken` from `createGrantRound`, instead using the immutable `donationToken` when creating a Round
- [x] Add an immutable variable `registry`, an instance of `GrantRegistry` to the Manager contract that is defined at deployment
- [x] Add an immutable variable `router`, an instance of the Uniswap v3 Router contract that is defined at deployment
- [ ] Define a new `Donation` struct as follows:

```solidity
// Define inputs required for each contribution in a struct
struct Donation {
  uint96 grantId; // grantId
  uint256 amount; // amount of that token
  address[] swapPath; // Uniswap router swap path
  address[] rounds; // rounds they want the contribution to count for
}
```

- [ ] Create a new method, `swapAndDonate`, which:
    - [ ]  Takes a a `Donation` struct as a parameter
    - [ ] Verifies the `grantId` is valid
    - [ ] Iterates over each `round`, validating it:
        - [ ] Is an active round (between start and end time)
        - [ ] Uses the `donationToken` defined by this Manager
    - [ ] IF `swapPath[0]` defined in `Donation` is the same as the Manager's `donationToken`, uses `transferFrom` to move the token to the Grant's `payee` address
    - [ ] Otherwise:
        - [ ] Use `transferFrom` to move `amount` of the token `swapPath[0]` to the Manager
        - [ ] Use `router` and `swapPath` to swap `swapPath[0]` for `donationToken`
        - [ ] Use `transfer` to send the `donationToken.balanceOf(this)` to the Grant's `payee` address
    - [ ] In both cases: emit an event with the `grantId`, `swapPath[0]` token, `amount`, and `rounds` included
- [ ] Remove `donateToGrant` from the `GrantRound` contract

**Comment by mds1** [comment]
Thanks for writing this up! Some thoughts/feedback below:

> Remove `_donationToken` from `createGrantRound`, instead using the immutable `donationToken` when creating a Round

I wanted to call this one out because my understanding was we'd still let rounds use their own `_donationToken` if they want. To clarify, there's two possibilities I see:
1. The quoted bullet's approach: If the factory uses GTC as the donation token, then for every round created by the grant manager (1) grant owners receive contributions in GTC, and (2) match payouts are also received in GTC
2. My prior understanding: The factory and rounds can have their own donation tokens, so if the grant manager uses GTC as the donation token, then (1) grant owners receive contributions in GTC, but (2) a grant round can use any token it wants for match payouts, and is not limited to GTC

> - Add an immutable variable registry, an instance of GrantRegistry to the Manager contract that is defined at deployment
>  - Add an immutable variable router, an instance of the Uniswap v3 Router contract that is defined at deployment

These imply that a change to the `GrantRegistry` OR the Uniswap Router also means deploying a new `GrantRoundManager`. So if we need to deploy a new GrantRegistry for some reason, or if Uniswap deploys a new router to fix a bug in their current router, then we also need a new GrantRoundManager. Maybe this is ok, or would we prefer to have an `owner` that can change these addresses? More generally, perhaps we create a separate issue to discuss upgrade/migration scenarios

>  Verifies the `grantId` is valid

This can be skipped because we need to read the `payee` address, so if the `grantId` is invalid that call will revert. However, explicitly verifying it beforehand means you can fail with a more useful error message. So the best way to handle this is to modify `GrantRegistry.getGrantPayee(_id)` to first validate that `_id < grantCount` and revert if not

> `swapAndDonate` Iterates over each round, validating it is an active round (between start and end time) and uses the donationToken defined by this Manager

If one of the validation checks fail, how should that be handled? Options are:
1. Ignore it and skip that loop iteration
2. Emit an `InvalidRound` (or similar) event then skip the loop iteration
3. Revert the full transaction

>  Use `transfer` to send the `donationToken.balanceOf(this)` to the Grant's payee address

This doesn't matter much for now, since this whole method is super inefficient/gas-guzzly as-is and will be optimized in the future, but you can do this transfer as part of the swap, since the [swap input arguments](https://github.com/Uniswap/uniswap-v3-periphery/blob/1f5b385675eee30a77ee10f4dfd6aa0aaa766026/contracts/interfaces/ISwapRouter.sol#L10-L19) take a `recipient` address.

In case the implementer decides to do the `transfer` approach for whatever reason, the amount transferred should really be the `amountOut` [returned](https://github.com/Uniswap/uniswap-v3-periphery/blob/1f5b385675eee30a77ee10f4dfd6aa0aaa766026/contracts/SwapRouter.sol#L120) by the swap. In addition to saving a call + storage read, this is also a bit more "correct" as it avoid donating any stray tokens in the contract to the grant owner

> emit an event with the `grantId`, `swapPath[0]` token, `amount`, and `rounds` included

The `amount` here is intended to be the swap output amount right? Though there's also an argument for emitting both the swap input _and_ output amounts as the former could be useful for UX (to show the user the amount they had in their cart, though you could also do this by decoding the tx input data), and the latter is for pricing used for match calculations
