### ISSUE TITLE
Breadcrumb Navigation Bugs

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#464]
Breadcrumb navigation is messed up

* View a round and the breadcrumbs are DGRANTS > ROUNDS > #0x123. This should either (1) have the round name instead of address, or (2) remove the pound sign in front of the address
* From that page, click "See Grants" and now breadcrumbs are DGRANTS > DGRANTS PROOF-OF-CONCEPT >, but it should be DGRANTS > ROUNDS > DGRANTS PROOF-OF-CONCEPT >
* Then click on the "Octavio leaving" grant, and breadcrumbs are DGRANTS > REGISTRY > #5, but (1) ideally the grant number is replaced with the name, and (2) the breadcrumbs changed entirely and no longer show round information
* Breadcrumbs will also get long once fixed, so need to make sure they wrap nicely or truncate nicely on mobile

**Comment by Ajand** [comment]
- [x] View a round and the breadcrumbs are DGRANTS > ROUNDS > #0x123. This should either (1) have the round name instead of address, or (2) remove the pound sign in front of the address
- [ ] From that page, click "See Grants" and now breadcrumbs are DGRANTS > DGRANTS PROOF-OF-CONCEPT >, but it should be DGRANTS > ROUNDS > DGRANTS PROOF-OF-CONCEPT >
- [ ] Then click on the "Octavio leaving" grant, and breadcrumbs are DGRANTS > REGISTRY > Re-import Original Prototype Contracts #5, but (1) ideally the grant number is replaced with the name, and (2) the breadcrumbs changed entirely and no longer show round information
- [ ] Breadcrumbs will also get long once fixed, so need to make sure they wrap nicely or truncate nicely on mobile
