### ISSUE TITLE
Grant Registry Requirements Implmentation

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#6]
- [ ] Global
- [ ] Store the data for each grant
- [ ] Anyone can create a grant
- [ ] Only the grant owner can update their grant
- [ ] Grant Registry needs to have an upgrade path itself

**Comment by mds1** [comment]
Regarding upgradeability, I'd like to discuss that a bit more. I have a two main thoughts here:

1. If the contract can be upgraded, someone (such as the Gitcoin DAO) needs special privileges, e.g. an owner. The current version of this contract is credibly neutral, but a version containing privileged roles is not. IMO this is a heavy downside, and makes it much more likely that additional `GrantRegistry` contracts may be deployed by other entities, which fragments the grants ecosystem. For example, in the current implementation of the Registry, no grant can be censored / blocked from creation, but a future version could add this. Therefore who doesn't trust the owner might therefore want to create their own registry instead

2. One reason for upgradeability might be to add more data to the `Grant` struct. However, we can work around that without needing to update the `GrantRegistry` implementation. A simple version of this is to add one more field to the grants struct of type `bytes extraData`. This `extraData` field can be set to anything, so allows for future extensibility specified by some (off-chain) encoding scheme. For (a totally random) example, say after the first round we say "It'd be useful if the `Grant` struct had a `lastUpdateTimestamp` and `lastMatchAmount` fields. Let's specify the first 16 bytes of `extraData` as the timestamp, and the next 24 bytes as the last match amount".  We'd of course need one more `update` method to let owners set the bytes field

Therefore, I think we should think about *what specifically* we may want to upgrade in the future, and try to think of ways to account for it now that don't require new contracts.

In the very worst case, if we really need new functionality later, you can deploy a `GrantRegistryV2` and initialize it with the `GrantRegistryV1` state, OR communicate to grant owners that they must migrate themselves and recreate their grant. Requiring a migration to a `GrantRegistryV2` (instead of an in-place update) is arguably a good thing as it clears state grants from state that frontends and curators need to handle

**Comment by apbendi** [comment]
I'm very sympathetic to this argument @mds1 and would be eager to hear what @phutchins and others think.

One contribution I'd make is that there are also gradations in between the DAO having total upgradeability powers, and no privileges whatsoever. One quick example: the DAO could have "pause" functionality, that let's them freeze the addition/removal of existing Grants, which would be useful in the migration to a would-be V2.

**Comment by apbendi** [comment]
Standup discussion:

* No upgradeability
* Revisit more specific privileges in the future, leaning toward no privileges in the base later

**Comment by mds1** [comment]
Closing this, and added a cart in https://github.com/orgs/dcgtc/projects/2 to track this decision
