### ISSUE TITLE
Site not working

### ISSUE THREAD

**Issue by JunaidPeer** [dcgtc/dgrants#616]
Hey just wanted to inform that the site is broken its just loading for me and others too.. 
![image](https://user-images.githubusercontent.com/87606844/149587912-a9c864a6-fa0f-4815-a03c-d0b455b3a873.png)
wondering what caused this.... the payout claim update?

**Comment by phutchins** [comment]
Hey and thanks for submitting this. This was caused by a user manually attempting to create a Grant Round via the contracts on chain. Our current implementation only accounts for a single round so it broke the UI. Payouts are currently a separate process and done independently of the UI. They went out a couple of days ago.
